### ISSUE TITLE
Issue with creation of STDMAE masks

### ISSUE THREAD

**Issue by malay-gaherwar** [GestaltCogTeam/BasicTS#165] opened 2024-10-27 11:25 UTC
Hello, I recently updated the library after you added the STDMAE to baselines. The error is as follows:

File "/home/user_name/anaconda3/envs/basicts/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'baselines/STDMAE/mask_save/TMAE_PEMS03_864.pt'

I created an empty TMAE_PEMS03_864.pt file so that maybe it could overwrite it. But that also did not help as it only read the empty file instead of overwriting it with the actual masks.

**Comment by zezhishao** [comment] 2024-10-27 11:57
Could you clarify what you mean by "creation of STDMAE masks"? According to the paper and the original implementation, TMAE is a pretraining model. The checkpoint `TMAE_PEMS03_864.pt` should be generated through the TMAE pretraining process, instead of STD-MAE. See https://github.com/Jimmy-7664/STD-MAE?tab=readme-ov-file#pre-training-on-s-mae-and-t-mae and https://github.com/GestaltCogTeam/BasicTS/blob/master/baselines/STDMAE/README.md.

**Comment by malay-gaherwar** [comment] 2024-10-27 16:21
I see. Thanks. But as my end goal is to train the model on my own dataset, I need to create my own checkpoints of the TMAE and SMAE. And for that I first try to replicate the creation of mask_saves on the PEMS03 data.
When I run the command  python experiments/train.py -c baselines/STDMAE/TMAE_PEMS03.py --gpus ''0'', the following error pops up which never popped up in the other implementations like STNorm, AGCRN.

File "/home/user_name/anaconda3/envs/basicts/lib/python3.9/site-packages/torch/functional.py", line 327, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by zezhishao** [comment] 2024-11-12 03:06
I’m unable to reproduce the error; the program appears to be working correctly with the current code. You might need to double-check any recent changes you've made.

**Comment by zezhishao** [comment] 2024-11-19 12:32
If there is no further discussion, this issue will be closed in one day.

**Closed** 2024-11-20 03:26 UTC
